apiVersion: v1
kind: Service
metadata:
  name: myapp-app
  namespace: myapp
  labels:
    app: myapp-app
spec:
  ports:
  - port: 8001
    targetPort: httpport
    name: http
  selector:
    app: myapp-app