// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package bookrepo

import (
	"context"
	"myapp/model"
	"strings"

	"github.com/google/uuid"
	"gorm.io/cli/gorm/typed"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func IBookRepo[T any](db *gorm.DB, opts ...clause.Expression) _IBookRepoInterface[T] {
	return _IBookRepoImpl[T]{
		Interface: typed.G[T](db, opts...),
	}
}

type _IBookRepoInterface[T any] interface {
	typed.Interface[T]
	ListBooks(ctx context.Context, limit int64, offset int64) (model.Books, error)
	CreateBook(ctx context.Context, data *model.Book) (*model.Book, error)
	ReadBook(ctx context.Context, id uuid.UUID) (*model.Book, error)
	UpdateBook(ctx context.Context, data *model.Book) (*model.Book, error)
	DeleteBook(ctx context.Context, id uuid.UUID) (bool, error)
}

type _IBookRepoImpl[T any] struct {
	typed.Interface[T]
}

func (e _IBookRepoImpl[T]) ListBooks(ctx context.Context, limit int64, offset int64) (model.Books, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM books LIMIT ? OFFSET ?")
	_params = append(_params, limit, offset)

	var result model.Books
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _IBookRepoImpl[T]) CreateBook(ctx context.Context, data *model.Book) (*model.Book, error) {
	var sb strings.Builder
	_params := make([]any, 0, 6)

	sb.WriteString("INSERT INTO books (id, created_at, updated_at, title, author, published_date, image_url, description) VALUES (?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?, ?, ?, ?)")
	_params = append(_params, data.ID, data.Title, data.Author, data.PublishedDate, data.ImageURL, data.Description)
	sb.WriteString(" RETURNING *")

	var result *model.Book
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _IBookRepoImpl[T]) ReadBook(ctx context.Context, id uuid.UUID) (*model.Book, error) {
	var sb strings.Builder
	_params := make([]any, 0, 1)

	sb.WriteString("SELECT * FROM books WHERE id = ?")
	_params = append(_params, id)

	var result *model.Book
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _IBookRepoImpl[T]) UpdateBook(ctx context.Context, data *model.Book) (*model.Book, error) {
	var sb strings.Builder
	_params := make([]any, 0, 6)

	sb.WriteString("UPDATE books")
	sb.WriteString(" SET updated_at=CURRENT_TIMESTAMP, title=?, author=?, published_date=?, image_url=?, description=?")
	_params = append(_params, data.Title, data.Author, data.PublishedDate, data.ImageURL, data.Description)
	sb.WriteString(" WHERE id = ?")
	_params = append(_params, data.ID)
	sb.WriteString(" RETURNING *")

	var result *model.Book
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _IBookRepoImpl[T]) DeleteBook(ctx context.Context, id uuid.UUID) (bool, error) {
	var sb strings.Builder
	_params := make([]any, 0, 1)

	sb.WriteString("DELETE FROM books WHERE id = ?")
	_params = append(_params, id)
	sb.WriteString(" RETURNING true")

	var result bool
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}
